import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Pencil, Receipt, Truck } from "lucide-react";
import { setTripPaymentStatus, transitionTrip } from "@/app/actions/trips";
import { requireUser } from "@/lib/auth/session";
import { prisma } from "@/lib/prisma";

const statusLabel = { SCHEDULED: "Programado", IN_PROGRESS: "En curso", COMPLETED: "Completado", CANCELLED: "Cancelado" };
const statusStyle = { SCHEDULED: "bg-blue-50 text-blue-700", IN_PROGRESS: "bg-amber-50 text-amber-700", COMPLETED: "bg-emerald-50 text-emerald-700", CANCELLED: "bg-zinc-100 text-zinc-500" };

export default async function TripDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireUser();
  const { id } = await params;
  const trip = await prisma.trip.findUnique({ where: { id }, include: {
    vehicle: { select: { id: true, economicNumber: true, brand: true, model: true } },
    driver: { select: { name: true, phone: true } },
    externalCarrier: { select: { id: true, businessName: true } },
    customerPaidBy: { select: { name: true, email: true } },
    subcontractorPaidBy: { select: { name: true, email: true } },
    expenses: { where: { status: "CONFIRMED" }, include: { items: true }, orderBy: { expenseDate: "desc" } },
  } });
  if (!trip) notFound();
  const finance = user.role !== "EMPLOYEE";
  const own = trip.executionType === "OWN";
  const totalCost = trip.expenses.reduce((sum, expense) => sum + Number(expense.total), 0);
  const distance = trip.mileageStart === null || trip.mileageEnd === null ? null : trip.mileageEnd - trip.mileageStart;
  const fuelExpenses = trip.expenses.filter((expense) => expense.category === "FUEL");
  const liters = fuelExpenses.flatMap((expense) => expense.items).filter((item) => ["l", "litro", "litros"].includes(item.unit?.toLowerCase() ?? "")).reduce((sum, item) => sum + Number(item.quantity), 0);
  const formatMoney = (value: number) => `$${value.toLocaleString("es-MX", { minimumFractionDigits: 2 })}`;
  const subcontractorCost = trip.subcontractorCost === null ? null : Number(trip.subcontractorCost);
  const subcontractedMargin = subcontractorCost === null ? null : Number(trip.revenue) - subcontractorCost;

  return <main className="min-h-screen bg-zinc-50"><div className="mx-auto max-w-6xl px-4 py-7 sm:px-6 lg:px-8">
    <Link href="/trips" className="inline-flex items-center gap-2 text-sm font-semibold text-company-700"><ArrowLeft className="size-4" /> Volver a viajes</Link>
    <header className="mt-5 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-3xl font-black text-zinc-900">{trip.tripNumber}</h1><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusStyle[trip.status]}`}>{statusLabel[trip.status]}</span><span className="rounded-full bg-zinc-100 px-2.5 py-1 text-xs font-semibold text-zinc-600">{own ? "Ejecución propia" : "Ejecución subcontratada"}</span></div><p className="mt-2 text-sm text-zinc-500">{trip.scheduledStartAt.toLocaleString("es-MX", { dateStyle: "full", timeStyle: "short", timeZone: "America/Mexico_City" })}</p></div><div className="flex flex-wrap gap-2">{finance && trip.status === "SCHEDULED" && <Link href={`/trips/${id}/edit`} className="inline-flex h-10 items-center gap-2 rounded-xl border border-zinc-200 bg-white px-4 text-sm font-semibold"><Pencil className="size-4" /> Editar</Link>}{finance && own && trip.vehicleId && trip.status !== "CANCELLED" && <Link href={`/fleet-expenses/new?tripId=${id}&vehicleId=${trip.vehicleId}`} className="inline-flex h-10 items-center gap-2 rounded-xl bg-company px-4 text-sm font-bold text-white"><Receipt className="size-4" /> Registrar gasto</Link>}</div></header>
    <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Cliente" value={trip.clientNameSnapshot} /><Metric label="Destino" value={`${trip.destinationNameSnapshot} · ${trip.destinationSnapshot}`} /><Metric label="Origen" value={trip.origin} />{own ? <><Metric label="Unidad" value={trip.vehicle ? `${trip.vehicle.economicNumber} · ${trip.vehicle.brand} ${trip.vehicle.model}` : "Sin unidad registrada"} /><Metric label="Operador" value={trip.driver?.name ?? "Sin operador registrado"} /><Metric label="Odómetro inicial" value={trip.mileageStart === null ? "No registrado" : `${trip.mileageStart.toLocaleString("es-MX")} km`} /><Metric label="Distancia recorrida" value={distance === null ? "Pendiente de cierre" : `${distance.toLocaleString("es-MX")} km`} /></> : <>{finance && trip.externalCarrierId ? <Link href={`/external-carriers/${trip.externalCarrierId}`} className="block rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm hover:border-company-300"><p className="text-xs font-medium text-zinc-400">Transportista</p><p className="mt-2 break-words text-sm font-semibold text-company-700">{trip.externalCarrierNameSnapshot ?? trip.externalCarrier?.businessName ?? "Sin transportista"}</p></Link> : <Metric label="Transportista" value={trip.externalCarrierNameSnapshot ?? trip.externalCarrier?.businessName ?? "Sin transportista"} />}<Metric label="Camión externo" value={trip.externalVehicleDescription ?? "Sin descripción"} /><Metric label="Operador externo" value={trip.externalDriverName ?? "Sin nombre"} /></>}{finance && <Metric label="Ingreso del cliente" value={formatMoney(Number(trip.revenue))} />}{finance && own && <Metric label="Costos confirmados" value={formatMoney(totalCost)} />}</section>

    {finance && (own ? trip.status === "COMPLETED" : true) && <section className="mt-5 rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-zinc-900">{own ? "Rendimiento del viaje" : "Resumen económico"}</h2>{own ? <div className="mt-4 grid gap-4 sm:grid-cols-3"><Metric label="Margen directo" value={formatMoney(Number(trip.revenue) - totalCost)} /><Metric label="Combustible registrado" value={`${liters.toLocaleString("es-MX", { maximumFractionDigits: 3 })} L`} /><Metric label="Rendimiento" value={distance && liters ? `${(distance / liters).toFixed(2)} km/L · ${(liters * 100 / distance).toFixed(2)} L/100 km` : "Requiere distancia y litros detallados"} /></div> : <><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Ingreso del cliente" value={formatMoney(Number(trip.revenue))} /><Metric label="Costo del transportista" value={subcontractorCost === null ? "Sin costo" : formatMoney(subcontractorCost)} /><Metric label="Margen" value={subcontractedMargin === null ? "Sin calcular" : formatMoney(subcontractedMargin)} /><PaymentMetric label="Cobranza" status={trip.customerPaymentStatus} /><PaymentMetric label="Pago al transportista" status={trip.subcontractorPaymentStatus} /></div>{subcontractedMargin !== null && subcontractedMargin < 0 && <p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm font-medium text-amber-800">El costo supera el ingreso; este viaje tiene margen negativo.</p>}
      <div className="mt-5 grid gap-4 border-t border-zinc-100 pt-4 sm:grid-cols-2"><PaymentControl tripId={id} payment="customer" status={trip.customerPaymentStatus} paidAt={trip.customerPaidAt} paidBy={trip.customerPaidBy?.name ?? trip.customerPaidBy?.email ?? null} label="Pago del cliente" /><PaymentControl tripId={id} payment="subcontractor" status={trip.subcontractorPaymentStatus} paidAt={trip.subcontractorPaidAt} paidBy={trip.subcontractorPaidBy?.name ?? trip.subcontractorPaidBy?.email ?? null} label="Pago al transportista" /></div></>}</section>}

    <section className="mt-5 rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-bold text-zinc-900"><Truck className="size-5 text-zinc-400" /> Seguimiento operativo</h2><div className="mt-4 flex flex-wrap gap-x-8 gap-y-3 text-sm text-zinc-600"><p>Salida: {trip.startedAt?.toLocaleString("es-MX", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Mexico_City" }) ?? "Sin iniciar"}</p><p>Cierre: {trip.completedAt?.toLocaleString("es-MX", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Mexico_City" }) ?? "Pendiente"}</p><p>Odómetro final: {trip.executionType === "SUBCONTRACTED" ? "No aplica" : trip.mileageEnd?.toLocaleString("es-MX") ?? "Pendiente"}{own && trip.mileageEnd !== null ? " km" : ""}</p></div>{trip.notes && <p className="mt-4 whitespace-pre-wrap border-t border-zinc-100 pt-4 text-sm text-zinc-600">{trip.notes}</p>}
      {(trip.status === "SCHEDULED" || trip.status === "IN_PROGRESS") && <div className="mt-5 flex flex-wrap gap-3 border-t border-zinc-100 pt-4">{trip.status === "SCHEDULED" && <form action={transitionTrip}><input type="hidden" name="id" value={id} /><input type="hidden" name="action" value="start" /><button className="h-10 rounded-xl bg-emerald-600 px-4 text-sm font-bold text-white">Iniciar viaje</button></form>}{trip.status === "IN_PROGRESS" && <form action={transitionTrip} className="flex flex-wrap items-end gap-2"><input type="hidden" name="id" value={id} /><input type="hidden" name="action" value="complete" />{own && <label className="text-xs font-medium text-zinc-600">Kilometraje final<input type="number" name="mileageEnd" required min={trip.mileageStart ?? 0} max={2147483647} className="mt-1 h-10 rounded-lg border border-zinc-200 px-3 text-sm" /></label>}{!own && <p className="text-sm text-zinc-500">No se requiere kilometraje para un viaje ejecutado por un tercero.</p>}<button className="h-10 rounded-xl bg-emerald-600 px-4 text-sm font-bold text-white">Completar viaje</button></form>}{finance && <form action={transitionTrip}><input type="hidden" name="id" value={id} /><input type="hidden" name="action" value="cancel" /><button className="h-10 rounded-xl border border-zinc-200 px-4 text-sm font-semibold text-zinc-600">Cancelar viaje</button></form>}</div>}
    </section>
    {finance && own && <section className="mt-5 overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-zinc-100 p-5"><div><h2 className="font-bold text-zinc-900">Gastos vinculados</h2><p className="mt-1 text-sm text-zinc-500">Solo los gastos confirmados forman parte del análisis.</p></div><Receipt className="size-5 text-zinc-400" /></div>{trip.expenses.length ? <div className="divide-y divide-zinc-100">{trip.expenses.map((expense) => <Link key={expense.id} href={`/fleet-expenses/${expense.id}`} className="flex items-center justify-between gap-4 p-4 hover:bg-zinc-50"><div><p className="font-semibold text-zinc-800">{expense.description}</p><p className="mt-1 text-xs text-zinc-500">{expense.expenseDate.toLocaleDateString("es-MX", { timeZone: "UTC" })} · {expense.category}</p></div><span className="text-sm font-bold text-zinc-800">{formatMoney(Number(expense.total))}</span></Link>)}</div> : <p className="p-6 text-sm text-zinc-500">Todavía no hay gastos confirmados para este viaje.</p>}</section>}
  </div></main>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm"><p className="text-xs font-medium text-zinc-400">{label}</p><p className="mt-2 break-words text-sm font-semibold text-zinc-800">{value}</p></div>; }
function PaymentMetric({ label, status }: { label: string; status: "PENDING" | "PAID" | null }) { return <div className="min-w-0 rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm"><p className="text-xs font-medium text-zinc-400">{label}</p><p className={`mt-2 text-sm font-semibold ${status === "PAID" ? "text-emerald-700" : "text-amber-700"}`}>{status === "PAID" ? "Pagado" : status === "PENDING" ? "Pendiente" : "No aplica"}</p></div>; }
function PaymentControl({ tripId, payment, status, paidAt, paidBy, label }: { tripId: string; payment: "customer" | "subcontractor"; status: "PENDING" | "PAID" | null; paidAt: Date | null; paidBy: string | null; label: string }) {
  if (!status) return null;
  const nextStatus = status === "PAID" ? "PENDING" : "PAID";
  return <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-zinc-50 p-3"><div><p className="text-sm font-semibold text-zinc-800">{label}: {status === "PAID" ? "Pagado" : "Pendiente"}</p>{paidAt && <p className="mt-1 text-xs text-zinc-500">Registrado {paidAt.toLocaleString("es-MX", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Mexico_City" })}{paidBy ? ` por ${paidBy}` : ""}</p>}</div><form action={setTripPaymentStatus}><input type="hidden" name="id" value={tripId} /><input type="hidden" name="payment" value={payment} /><input type="hidden" name="status" value={nextStatus} /><button className="rounded-lg border border-zinc-200 bg-white px-3 py-2 text-xs font-semibold text-zinc-700">Marcar como {nextStatus === "PAID" ? "pagado" : "pendiente"}</button></form></div>;
}
